private object Version {
    const val MATERIAL = "1.2.0-alpha05"
    const val LIFECYCLE = "2.2.0"
    const val CONSTRAINT = "2.0.0-beta4"
    const val KOIN = "2.1.4"
    const val GLIDE = "4.11.0"
    const val VIEWPAGER2 = "1.0.0"
    const val NAVIGATION = "2.3.0-alpha03"
    const val ROOM = "2.2.4"
    const val TIMBER = "4.7.1"
    const val STETHO = "1.5.1"
    const val RETROFIT = "2.7.1"
    const val PAGING = "2.1.1"
    const val COROUTINE = "1.3.4"
    const val LEAK_CANARY = "2.2"
    const val OKHTTP_LOGGING = "4.4.0"
}

object Library {
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${CoreVersion.KOTLIN}"
    const val VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.LIFECYCLE}"
    const val MATERIAL = "com.google.android.material:material:${Version.MATERIAL}"
    const val CONSTRAINT = "androidx.constraintlayout:constraintlayout:${Version.CONSTRAINT}"
    const val KOIN = "org.koin:koin-androidx-viewmodel:${Version.KOIN}"
    const val GLIDE = "com.github.bumptech.glide:glide:${Version.GLIDE}"
    const val VIEWPAGER2 = "androidx.viewpager2:viewpager2:${Version.VIEWPAGER2}"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:${Version.NAVIGATION}"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx:${Version.NAVIGATION}"
    const val NAVIGATION_DYNAMIC_FEATURE = "androidx.navigation:navigation-dynamic-features-fragment:${Version.NAVIGATION}"
    const val ROOM = "androidx.room:room-runtime:${Version.ROOM}"
    const val ROOM_KTX = "androidx.room:room-ktx:${Version.ROOM}"
    const val TIMBER = "com.jakewharton.timber:timber:${Version.TIMBER}"
    const val STETHO = "com.facebook.stetho:stetho:${Version.STETHO}"
    const val STETHO_OKHTTP = "com.facebook.stetho:stetho-okhttp3:${Version.STETHO}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Version.RETROFIT}"
    const val RETROFIT_CONVERTER = "com.squareup.retrofit2:converter-gson:${Version.RETROFIT}"
    const val OKHTTP_LOGGING = "com.squareup.okhttp3:logging-interceptor:${Version.OKHTTP_LOGGING}"
    const val PAGING = "androidx.paging:paging-runtime-ktx:${Version.PAGING}"
    const val COROUTINE = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.COROUTINE}"
    const val LEAK_CANARY = "com.squareup.leakcanary:leakcanary-android:${Version.LEAK_CANARY}"

    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler:${Version.GLIDE}"
    const val ROOM_COMPILER = "androidx.room:room-compiler:${Version.ROOM}"
}